version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo Installing AWS CLI and jq on Ubuntu...
      - apt-get update -y
      - apt-get install -y awscli jq

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 940482407187.dkr.ecr.eu-north-1.amazonaws.com)

  build:
    commands:
      - echo Building Docker image...
      - docker build -t my-docker-image .
      - docker tag my-docker-image:latest 940482407187.dkr.ecr.eu-north-1.amazonaws.com/my-docker-repo:latest

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push 940482407187.dkr.ecr.eu-north-1.amazonaws.com/my-docker-repo:latest
      - echo "Image URI: 940482407187.dkr.ecr.eu-north-1.amazonaws.com/my-docker-repo:latest"

artifacts:
  files:
    - '**/*'
  discard-paths: yes
  base-directory: build-output
